### PR TITLE
Issue 9/task/email address spec

### LINKED ISSUE #9: email address specification
Implement the logic to store, update and delete the email address of specific users. Email addresses are needed to send reminders and attachments to users via email.

### PR DESCRIPTION
**Pull request by chandur626**
This PR contains changes related to email address configuration. Users now will be able to configure their email addresses to receive notifications and file attachments. Tests for the same are defined in the test_email_address file and the following things are taken off.
1.) complies with pylint.
2.) no effect on coverage.

### CODE REVIEW

**Comment by nirajlavani** [comment]
What's the significance of the is_active column in email_address table?

**Comment by chandur626** [comment]
> What's the significance of the is_active column in email_address table?

It indicates whether that particular record in the table is active or not.

**Comment by SriPallaviDamuluri** [comment]
are we really deleting the email records from the db?

**Comment by chandur626** [comment]
> are we really deleting the email records from the DB?

We are maintaining a column is_active for the same. In the case of delete, the is_active is set to false.

**Review by 05sandesh — APPROVED** [review]

**Review by HariniBharata — APPROVED** [review]
approved.

**Pull request merged**
