### PR TITLE
Issue-2/task/implement email utility

### LINKED ISSUE #2: Implement the email Utility.
Email would be another important source of communication that can be established through discord. Implement the email utility which acts as a wrapper to send emails of plain messages and attachments.

### PR DESCRIPTION
**Pull request by chandur626**
This pull request consists of changes related to email utility implementation. The email utility handles both multipart attachments and plain body text. The test cases for the same had been added to the test_email_utility file under the test directory. Implementation complies with pylint and there is no effect on coverage.

### CODE REVIEW

**Comment by nirajlavani** [comment]
Will this email utility handle plain-text and/or multipart?

**Review by 05sandesh — COMMENTED** [review]
can we send multiple attachments in the same mail?

**Comment by HariniBharata** [comment]
Can we send to multiple email addresses at the same time?

**Comment by chandur626** [comment]
> Will this email utility handle plain-text and/or multipart?

Yes, it handles both plain text and multi_part. Hence, the parameter attachment in email utility send_email function.

**Comment by chandur626** [comment]
> Can we send to multiple email addresses at the same time?

yes, the to_address parameter accepts a list of the email addresses.

**Comment by chandur626** [comment]
> can we send multiple attachments in the same mail?

No, this was not implemented as part of this, can raise a new issue and work on it.

**Pull request merged**
