### PR TITLE
Issue 23/task/regrade request command

### PR DESCRIPTION
**Pull request by SriPallaviDamuluri**

### CODE REVIEW

**Comment by chandur626** [comment]
Are the duplicate requests being handled i.e if the same request is being raised by the same user?

**Comment by chandur626** [comment]
What if the format of the questions is not entered properly, is that case handled?

**Comment by nirajlavani** [comment]
Has the help command been updated to include this feature?

**Comment by SriPallaviDamuluri** [comment]
> Are the duplicate requests being handled i.e if the same request is being raised by the same user?

Yes this is taken care and we are re-directing to use update commands in order to make any changes.

**Comment by SriPallaviDamuluri** [comment]
> Has the help command been updated to include this feature?

Yes. added

**Comment by SriPallaviDamuluri** [comment]
> Are the duplicate requests being handled i.e if the same request is being raised by the same user?



> What if the format of the questions is not entered properly, is that case handled?

Yes, if the format doesn't match the regex expression, we are asking them to retry by showing an example.

**Review by HariniBharata — APPROVED** [review]
Approved

**Review by chandur626 — APPROVED** [review]

**Comment by SriPallaviDamuluri** [comment]
closes #36 #35 #23 #24 #25 #26 #27

**Comment by SriPallaviDamuluri** [comment]
closes #28

**Pull request merged**
