### PR TITLE
Issue 12/task/admin charts

### PR DESCRIPTION
**Pull request by nirajlavani**
- Admin tools to make a chart of any kind
- Student command to recall chart after creation

### CODE REVIEW

**Comment by chandur626** [comment]
Are we storing the charts to retrieve at a later point in time?

**Comment by chandur626** [comment]
What all kinds of charts a user can create?

**Review by chandur626 — APPROVED** [review]

**Review by 05sandesh — APPROVED** [review]

**Comment by nirajlavani** [comment]
> Are we storing the charts to retrieve at a later point in time?

Yeah the charts are stored locally in a .json file for user retrieval

**Comment by nirajlavani** [comment]
> What all kinds of charts a user can create?

The user can create charts like Pie, Doughnut, Line, and Bar.

**Review by HariniBharata — APPROVED** [review]
Approved.

**Pull request merged**
