### PR TITLE
adding the logic to email reminders due today

### PR DESCRIPTION
**Pull request by chandur626**
This PR consists of changes related to sending reminders regarding assignments due for less than a day.

### CODE REVIEW

**Comment by SriPallaviDamuluri** [comment]
looks good

**Review by HariniBharata — APPROVED** [review]

**Comment by nirajlavani** [comment]
Where are we getting the test recipient email variable?

**Comment by chandur626** [comment]
> Where are we getting the test recipient email variable?

There is a repository secret defined for the same.

**Review by 05sandesh — COMMENTED** [review]
Hi @chandur626, does "check_reminders_due_today" function handles all the functionalities we discussed

**Comment by chandur626** [comment]
> Hi @chandur626, does "check_reminders_due_today" function handles all the functionalities we discussed

Yeah it handles assignments and project events.

**Review by SriPallaviDamuluri — APPROVED** [review]

**Review by nirajlavani — APPROVED** [review]
Looks correct to me

**Review by 05sandesh — APPROVED** [review]

**Pull request merged**
